import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { paths } from './paths.ts';

// Bearer auth for the headless daemon. Two tokens are accepted:
//
// - The **pairing token** (`helm_rt_…`), generated by `pnpm remote:init`,
//   shown once, and held by the paired local helm. Only its SHA-256 hash is
//   stored on disk (.helm/remote.json) — the daemon can verify it but never
//   reproduce it.
// - The **internal token**, random per daemon process and never persisted.
//   It's injected into spawned agents (HELM_INTERNAL_TOKEN) so their
//   materialized tool scripts (helm/heartbeat/send-telegram) can call back
//   into the daemon without holding the pairing credential.

// Bitcoin-style base58: no 0/O/I/l, safe to read aloud and double-click-select.
const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

export function encodeBase58(buf: Uint8Array): string {
  let n = 0n;
  for (const b of buf) n = (n << 8n) | BigInt(b);
  let out = '';
  while (n > 0n) {
    out = ALPHABET[Number(n % 58n)] + out;
    n /= 58n;
  }
  // Leading zero bytes carry no magnitude; preserve them explicitly.
  for (const b of buf) {
    if (b !== 0) break;
    out = ALPHABET[0] + out;
  }
  return out;
}

export const TOKEN_PREFIX = 'helm_rt_';

export function generatePairingToken(): string {
  return TOKEN_PREFIX + encodeBase58(randomBytes(32));
}

export function hashToken(token: string): string {
  return createHash('sha256').update(token).digest('hex');
}

/** Shape of .helm/remote.json, written by `pnpm remote:init`. */
export interface RemoteJson {
  tokenHash: string;
  createdAt: string;
  helmVersion: string;
  /** Whether init's `claude -p ping` smoke test passed. */
  smokeOk?: boolean;
}

export function readRemoteJson(): RemoteJson | null {
  try {
    return JSON.parse(readFileSync(paths.remoteJson, 'utf8')) as RemoteJson;
  } catch {
    return null;
  }
}

// Cached at first use: the auth path stays pure CPU per request. Token
// rotation (`remote:init --rotate`) therefore requires a daemon restart —
// the rotate flow restarts the systemd unit and says so.
let cachedTokenHash: string | null | undefined;

export function loadTokenHash(): string | null {
  if (cachedTokenHash === undefined) {
    const json = readRemoteJson();
    cachedTokenHash = typeof json?.tokenHash === 'string' ? json.tokenHash : null;
  }
  return cachedTokenHash;
}

/**
 * Per-process token for the daemon's own agents. globalThis-cached so dev HMR
 * doesn't mint a new one mid-session (spawned agents hold the old value).
 */
export function getInternalToken(): string {
  const g = globalThis as { __helmInternalToken?: string };
  g.__helmInternalToken ??= encodeBase58(randomBytes(24));
  return g.__helmInternalToken;
}

// Hash both sides before comparing so timingSafeEqual sees fixed-length
// buffers — no early exit on length mismatch.
function digestEqual(a: string, b: string): boolean {
  return timingSafeEqual(
    createHash('sha256').update(a).digest(),
    createHash('sha256').update(b).digest(),
  );
}

/**
 * Validate an Authorization header against the internal token and the stored
 * pairing-token hash. Fail-closed: no header, no parse, or no stored hash
 * (when the pairing token is offered) all reject.
 *
 * `overrides` exists for unit tests — production callers pass the header only.
 */
export function verifyBearer(
  header: string | null,
  overrides?: { tokenHash?: string | null; internalToken?: string },
): boolean {
  if (!header) return false;
  const match = /^Bearer\s+(.+)$/i.exec(header);
  if (!match) return false;
  const token = match[1].trim();

  const internal = overrides?.internalToken ?? getInternalToken();
  if (digestEqual(token, internal)) return true;

  const tokenHash = overrides ? (overrides.tokenHash ?? null) : loadTokenHash();
  if (!tokenHash) return false;
  return digestEqual(hashToken(token), tokenHash);
}
