/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as RemotesRouteImport } from './routes/remotes'
import { Route as CaptainRouteImport } from './routes/captain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiToolsRouteImport } from './routes/api/tools'
import { Route as ApiRemotesRouteImport } from './routes/api/remotes'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiToolsIdRouteImport } from './routes/api/tools.$id'
import { Route as ApiSystemStatusRouteImport } from './routes/api/system.status'
import { Route as ApiSystemResumeRouteImport } from './routes/api/system.resume'
import { Route as ApiSystemPauseRouteImport } from './routes/api/system.pause'
import { Route as ApiRemotesIdRouteImport } from './routes/api/remotes.$id'
import { Route as ApiRemoteResumeRouteImport } from './routes/api/remote.resume'
import { Route as ApiRemotePauseRouteImport } from './routes/api/remote.pause'
import { Route as ApiRemoteInfoRouteImport } from './routes/api/remote.info'
import { Route as ApiRemoteImportRouteImport } from './routes/api/remote.import'
import { Route as ApiAgentsListRouteImport } from './routes/api/agents.list'
import { Route as ApiAgentsCreateRouteImport } from './routes/api/agents.create'
import { Route as ApiRemotesIdPingRouteImport } from './routes/api/remotes_.$id.ping'
import { Route as ApiRemotesIdPauseRouteImport } from './routes/api/remotes_.$id.pause'
import { Route as ApiAgentsIdToolsRouteImport } from './routes/api/agents.$id.tools'
import { Route as ApiAgentsIdShipRouteImport } from './routes/api/agents.$id.ship'
import { Route as ApiAgentsIdRunsRouteImport } from './routes/api/agents.$id.runs'
import { Route as ApiAgentsIdMessagesRouteImport } from './routes/api/agents.$id.messages'
import { Route as ApiAgentsIdInfoRouteImport } from './routes/api/agents.$id.info'
import { Route as ApiAgentsIdHeartbeatsRouteImport } from './routes/api/agents.$id.heartbeats'
import { Route as ApiAgentsIdChatRouteImport } from './routes/api/agents.$id.chat'
import { Route as ApiRemoteAgentsIdStatusRouteImport } from './routes/api/remote.agents.$id.status'
import { Route as ApiRemoteAgentsIdExportRouteImport } from './routes/api/remote.agents.$id.export'
import { Route as ApiRemoteAgentsIdDeleteRouteImport } from './routes/api/remote.agents.$id.delete'
import { Route as ApiAgentsIdToolsToolIdRouteImport } from './routes/api/agents.$id.tools.$toolId'
import { Route as ApiAgentsIdHeartbeatsHbIdRouteImport } from './routes/api/agents.$id.heartbeats.$hbId'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotesRoute = RemotesRouteImport.update({
  id: '/remotes',
  path: '/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainRoute = CaptainRouteImport.update({
  id: '/captain',
  path: '/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRoute = ApiToolsRouteImport.update({
  id: '/api/tools',
  path: '/api/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotesRoute = ApiRemotesRouteImport.update({
  id: '/api/remotes',
  path: '/api/remotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsIdRoute = ApiToolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiToolsRoute,
} as any)
const ApiSystemStatusRoute = ApiSystemStatusRouteImport.update({
  id: '/api/system/status',
  path: '/api/system/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemResumeRoute = ApiSystemResumeRouteImport.update({
  id: '/api/system/resume',
  path: '/api/system/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSystemPauseRoute = ApiSystemPauseRouteImport.update({
  id: '/api/system/pause',
  path: '/api/system/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotesIdRoute = ApiRemotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRemotesRoute,
} as any)
const ApiRemoteResumeRoute = ApiRemoteResumeRouteImport.update({
  id: '/api/remote/resume',
  path: '/api/remote/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotePauseRoute = ApiRemotePauseRouteImport.update({
  id: '/api/remote/pause',
  path: '/api/remote/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteInfoRoute = ApiRemoteInfoRouteImport.update({
  id: '/api/remote/info',
  path: '/api/remote/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteImportRoute = ApiRemoteImportRouteImport.update({
  id: '/api/remote/import',
  path: '/api/remote/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsListRoute = ApiAgentsListRouteImport.update({
  id: '/api/agents/list',
  path: '/api/agents/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsCreateRoute = ApiAgentsCreateRouteImport.update({
  id: '/api/agents/create',
  path: '/api/agents/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotesIdPingRoute = ApiRemotesIdPingRouteImport.update({
  id: '/api/remotes_/$id/ping',
  path: '/api/remotes/$id/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemotesIdPauseRoute = ApiRemotesIdPauseRouteImport.update({
  id: '/api/remotes_/$id/pause',
  path: '/api/remotes/$id/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdToolsRoute = ApiAgentsIdToolsRouteImport.update({
  id: '/api/agents/$id/tools',
  path: '/api/agents/$id/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdShipRoute = ApiAgentsIdShipRouteImport.update({
  id: '/api/agents/$id/ship',
  path: '/api/agents/$id/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdRunsRoute = ApiAgentsIdRunsRouteImport.update({
  id: '/api/agents/$id/runs',
  path: '/api/agents/$id/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdMessagesRoute = ApiAgentsIdMessagesRouteImport.update({
  id: '/api/agents/$id/messages',
  path: '/api/agents/$id/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdInfoRoute = ApiAgentsIdInfoRouteImport.update({
  id: '/api/agents/$id/info',
  path: '/api/agents/$id/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdHeartbeatsRoute = ApiAgentsIdHeartbeatsRouteImport.update({
  id: '/api/agents/$id/heartbeats',
  path: '/api/agents/$id/heartbeats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdChatRoute = ApiAgentsIdChatRouteImport.update({
  id: '/api/agents/$id/chat',
  path: '/api/agents/$id/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteAgentsIdStatusRoute = ApiRemoteAgentsIdStatusRouteImport.update({
  id: '/api/remote/agents/$id/status',
  path: '/api/remote/agents/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteAgentsIdExportRoute = ApiRemoteAgentsIdExportRouteImport.update({
  id: '/api/remote/agents/$id/export',
  path: '/api/remote/agents/$id/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteAgentsIdDeleteRoute = ApiRemoteAgentsIdDeleteRouteImport.update({
  id: '/api/remote/agents/$id/delete',
  path: '/api/remote/agents/$id/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdToolsToolIdRoute = ApiAgentsIdToolsToolIdRouteImport.update({
  id: '/$toolId',
  path: '/$toolId',
  getParentRoute: () => ApiAgentsIdToolsRoute,
} as any)
const ApiAgentsIdHeartbeatsHbIdRoute =
  ApiAgentsIdHeartbeatsHbIdRouteImport.update({
    id: '/$hbId',
    path: '/$hbId',
    getParentRoute: () => ApiAgentsIdHeartbeatsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captain': typeof CaptainRoute
  '/remotes': typeof RemotesRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/remotes': typeof ApiRemotesRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/api/agents/create': typeof ApiAgentsCreateRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/remote/import': typeof ApiRemoteImportRoute
  '/api/remote/info': typeof ApiRemoteInfoRoute
  '/api/remote/pause': typeof ApiRemotePauseRoute
  '/api/remote/resume': typeof ApiRemoteResumeRoute
  '/api/remotes/$id': typeof ApiRemotesIdRoute
  '/api/system/pause': typeof ApiSystemPauseRoute
  '/api/system/resume': typeof ApiSystemResumeRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/tools/$id': typeof ApiToolsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
  '/api/agents/$id/heartbeats': typeof ApiAgentsIdHeartbeatsRouteWithChildren
  '/api/agents/$id/info': typeof ApiAgentsIdInfoRoute
  '/api/agents/$id/messages': typeof ApiAgentsIdMessagesRoute
  '/api/agents/$id/runs': typeof ApiAgentsIdRunsRoute
  '/api/agents/$id/ship': typeof ApiAgentsIdShipRoute
  '/api/agents/$id/tools': typeof ApiAgentsIdToolsRouteWithChildren
  '/api/remotes/$id/pause': typeof ApiRemotesIdPauseRoute
  '/api/remotes/$id/ping': typeof ApiRemotesIdPingRoute
  '/api/agents/$id/heartbeats/$hbId': typeof ApiAgentsIdHeartbeatsHbIdRoute
  '/api/agents/$id/tools/$toolId': typeof ApiAgentsIdToolsToolIdRoute
  '/api/remote/agents/$id/delete': typeof ApiRemoteAgentsIdDeleteRoute
  '/api/remote/agents/$id/export': typeof ApiRemoteAgentsIdExportRoute
  '/api/remote/agents/$id/status': typeof ApiRemoteAgentsIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captain': typeof CaptainRoute
  '/remotes': typeof RemotesRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/remotes': typeof ApiRemotesRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/api/agents/create': typeof ApiAgentsCreateRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/remote/import': typeof ApiRemoteImportRoute
  '/api/remote/info': typeof ApiRemoteInfoRoute
  '/api/remote/pause': typeof ApiRemotePauseRoute
  '/api/remote/resume': typeof ApiRemoteResumeRoute
  '/api/remotes/$id': typeof ApiRemotesIdRoute
  '/api/system/pause': typeof ApiSystemPauseRoute
  '/api/system/resume': typeof ApiSystemResumeRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/tools/$id': typeof ApiToolsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
  '/api/agents/$id/heartbeats': typeof ApiAgentsIdHeartbeatsRouteWithChildren
  '/api/agents/$id/info': typeof ApiAgentsIdInfoRoute
  '/api/agents/$id/messages': typeof ApiAgentsIdMessagesRoute
  '/api/agents/$id/runs': typeof ApiAgentsIdRunsRoute
  '/api/agents/$id/ship': typeof ApiAgentsIdShipRoute
  '/api/agents/$id/tools': typeof ApiAgentsIdToolsRouteWithChildren
  '/api/remotes/$id/pause': typeof ApiRemotesIdPauseRoute
  '/api/remotes/$id/ping': typeof ApiRemotesIdPingRoute
  '/api/agents/$id/heartbeats/$hbId': typeof ApiAgentsIdHeartbeatsHbIdRoute
  '/api/agents/$id/tools/$toolId': typeof ApiAgentsIdToolsToolIdRoute
  '/api/remote/agents/$id/delete': typeof ApiRemoteAgentsIdDeleteRoute
  '/api/remote/agents/$id/export': typeof ApiRemoteAgentsIdExportRoute
  '/api/remote/agents/$id/status': typeof ApiRemoteAgentsIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captain': typeof CaptainRoute
  '/remotes': typeof RemotesRoute
  '/tools': typeof ToolsRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/remotes': typeof ApiRemotesRouteWithChildren
  '/api/tools': typeof ApiToolsRouteWithChildren
  '/api/agents/create': typeof ApiAgentsCreateRoute
  '/api/agents/list': typeof ApiAgentsListRoute
  '/api/remote/import': typeof ApiRemoteImportRoute
  '/api/remote/info': typeof ApiRemoteInfoRoute
  '/api/remote/pause': typeof ApiRemotePauseRoute
  '/api/remote/resume': typeof ApiRemoteResumeRoute
  '/api/remotes/$id': typeof ApiRemotesIdRoute
  '/api/system/pause': typeof ApiSystemPauseRoute
  '/api/system/resume': typeof ApiSystemResumeRoute
  '/api/system/status': typeof ApiSystemStatusRoute
  '/api/tools/$id': typeof ApiToolsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
  '/api/agents/$id/heartbeats': typeof ApiAgentsIdHeartbeatsRouteWithChildren
  '/api/agents/$id/info': typeof ApiAgentsIdInfoRoute
  '/api/agents/$id/messages': typeof ApiAgentsIdMessagesRoute
  '/api/agents/$id/runs': typeof ApiAgentsIdRunsRoute
  '/api/agents/$id/ship': typeof ApiAgentsIdShipRoute
  '/api/agents/$id/tools': typeof ApiAgentsIdToolsRouteWithChildren
  '/api/remotes_/$id/pause': typeof ApiRemotesIdPauseRoute
  '/api/remotes_/$id/ping': typeof ApiRemotesIdPingRoute
  '/api/agents/$id/heartbeats/$hbId': typeof ApiAgentsIdHeartbeatsHbIdRoute
  '/api/agents/$id/tools/$toolId': typeof ApiAgentsIdToolsToolIdRoute
  '/api/remote/agents/$id/delete': typeof ApiRemoteAgentsIdDeleteRoute
  '/api/remote/agents/$id/export': typeof ApiRemoteAgentsIdExportRoute
  '/api/remote/agents/$id/status': typeof ApiRemoteAgentsIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captain'
    | '/remotes'
    | '/tools'
    | '/agents/$id'
    | '/api/remotes'
    | '/api/tools'
    | '/api/agents/create'
    | '/api/agents/list'
    | '/api/remote/import'
    | '/api/remote/info'
    | '/api/remote/pause'
    | '/api/remote/resume'
    | '/api/remotes/$id'
    | '/api/system/pause'
    | '/api/system/resume'
    | '/api/system/status'
    | '/api/tools/$id'
    | '/api/trpc/$'
    | '/api/agents/$id/chat'
    | '/api/agents/$id/heartbeats'
    | '/api/agents/$id/info'
    | '/api/agents/$id/messages'
    | '/api/agents/$id/runs'
    | '/api/agents/$id/ship'
    | '/api/agents/$id/tools'
    | '/api/remotes/$id/pause'
    | '/api/remotes/$id/ping'
    | '/api/agents/$id/heartbeats/$hbId'
    | '/api/agents/$id/tools/$toolId'
    | '/api/remote/agents/$id/delete'
    | '/api/remote/agents/$id/export'
    | '/api/remote/agents/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captain'
    | '/remotes'
    | '/tools'
    | '/agents/$id'
    | '/api/remotes'
    | '/api/tools'
    | '/api/agents/create'
    | '/api/agents/list'
    | '/api/remote/import'
    | '/api/remote/info'
    | '/api/remote/pause'
    | '/api/remote/resume'
    | '/api/remotes/$id'
    | '/api/system/pause'
    | '/api/system/resume'
    | '/api/system/status'
    | '/api/tools/$id'
    | '/api/trpc/$'
    | '/api/agents/$id/chat'
    | '/api/agents/$id/heartbeats'
    | '/api/agents/$id/info'
    | '/api/agents/$id/messages'
    | '/api/agents/$id/runs'
    | '/api/agents/$id/ship'
    | '/api/agents/$id/tools'
    | '/api/remotes/$id/pause'
    | '/api/remotes/$id/ping'
    | '/api/agents/$id/heartbeats/$hbId'
    | '/api/agents/$id/tools/$toolId'
    | '/api/remote/agents/$id/delete'
    | '/api/remote/agents/$id/export'
    | '/api/remote/agents/$id/status'
  id:
    | '__root__'
    | '/'
    | '/captain'
    | '/remotes'
    | '/tools'
    | '/agents/$id'
    | '/api/remotes'
    | '/api/tools'
    | '/api/agents/create'
    | '/api/agents/list'
    | '/api/remote/import'
    | '/api/remote/info'
    | '/api/remote/pause'
    | '/api/remote/resume'
    | '/api/remotes/$id'
    | '/api/system/pause'
    | '/api/system/resume'
    | '/api/system/status'
    | '/api/tools/$id'
    | '/api/trpc/$'
    | '/api/agents/$id/chat'
    | '/api/agents/$id/heartbeats'
    | '/api/agents/$id/info'
    | '/api/agents/$id/messages'
    | '/api/agents/$id/runs'
    | '/api/agents/$id/ship'
    | '/api/agents/$id/tools'
    | '/api/remotes_/$id/pause'
    | '/api/remotes_/$id/ping'
    | '/api/agents/$id/heartbeats/$hbId'
    | '/api/agents/$id/tools/$toolId'
    | '/api/remote/agents/$id/delete'
    | '/api/remote/agents/$id/export'
    | '/api/remote/agents/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptainRoute: typeof CaptainRoute
  RemotesRoute: typeof RemotesRoute
  ToolsRoute: typeof ToolsRoute
  AgentsIdRoute: typeof AgentsIdRoute
  ApiRemotesRoute: typeof ApiRemotesRouteWithChildren
  ApiToolsRoute: typeof ApiToolsRouteWithChildren
  ApiAgentsCreateRoute: typeof ApiAgentsCreateRoute
  ApiAgentsListRoute: typeof ApiAgentsListRoute
  ApiRemoteImportRoute: typeof ApiRemoteImportRoute
  ApiRemoteInfoRoute: typeof ApiRemoteInfoRoute
  ApiRemotePauseRoute: typeof ApiRemotePauseRoute
  ApiRemoteResumeRoute: typeof ApiRemoteResumeRoute
  ApiSystemPauseRoute: typeof ApiSystemPauseRoute
  ApiSystemResumeRoute: typeof ApiSystemResumeRoute
  ApiSystemStatusRoute: typeof ApiSystemStatusRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiAgentsIdChatRoute: typeof ApiAgentsIdChatRoute
  ApiAgentsIdHeartbeatsRoute: typeof ApiAgentsIdHeartbeatsRouteWithChildren
  ApiAgentsIdInfoRoute: typeof ApiAgentsIdInfoRoute
  ApiAgentsIdMessagesRoute: typeof ApiAgentsIdMessagesRoute
  ApiAgentsIdRunsRoute: typeof ApiAgentsIdRunsRoute
  ApiAgentsIdShipRoute: typeof ApiAgentsIdShipRoute
  ApiAgentsIdToolsRoute: typeof ApiAgentsIdToolsRouteWithChildren
  ApiRemotesIdPauseRoute: typeof ApiRemotesIdPauseRoute
  ApiRemotesIdPingRoute: typeof ApiRemotesIdPingRoute
  ApiRemoteAgentsIdDeleteRoute: typeof ApiRemoteAgentsIdDeleteRoute
  ApiRemoteAgentsIdExportRoute: typeof ApiRemoteAgentsIdExportRoute
  ApiRemoteAgentsIdStatusRoute: typeof ApiRemoteAgentsIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotes': {
      id: '/remotes'
      path: '/remotes'
      fullPath: '/remotes'
      preLoaderRoute: typeof RemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captain': {
      id: '/captain'
      path: '/captain'
      fullPath: '/captain'
      preLoaderRoute: typeof CaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools': {
      id: '/api/tools'
      path: '/api/tools'
      fullPath: '/api/tools'
      preLoaderRoute: typeof ApiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remotes': {
      id: '/api/remotes'
      path: '/api/remotes'
      fullPath: '/api/remotes'
      preLoaderRoute: typeof ApiRemotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools/$id': {
      id: '/api/tools/$id'
      path: '/$id'
      fullPath: '/api/tools/$id'
      preLoaderRoute: typeof ApiToolsIdRouteImport
      parentRoute: typeof ApiToolsRoute
    }
    '/api/system/status': {
      id: '/api/system/status'
      path: '/api/system/status'
      fullPath: '/api/system/status'
      preLoaderRoute: typeof ApiSystemStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/resume': {
      id: '/api/system/resume'
      path: '/api/system/resume'
      fullPath: '/api/system/resume'
      preLoaderRoute: typeof ApiSystemResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/system/pause': {
      id: '/api/system/pause'
      path: '/api/system/pause'
      fullPath: '/api/system/pause'
      preLoaderRoute: typeof ApiSystemPauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remotes/$id': {
      id: '/api/remotes/$id'
      path: '/$id'
      fullPath: '/api/remotes/$id'
      preLoaderRoute: typeof ApiRemotesIdRouteImport
      parentRoute: typeof ApiRemotesRoute
    }
    '/api/remote/resume': {
      id: '/api/remote/resume'
      path: '/api/remote/resume'
      fullPath: '/api/remote/resume'
      preLoaderRoute: typeof ApiRemoteResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/pause': {
      id: '/api/remote/pause'
      path: '/api/remote/pause'
      fullPath: '/api/remote/pause'
      preLoaderRoute: typeof ApiRemotePauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/info': {
      id: '/api/remote/info'
      path: '/api/remote/info'
      fullPath: '/api/remote/info'
      preLoaderRoute: typeof ApiRemoteInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/import': {
      id: '/api/remote/import'
      path: '/api/remote/import'
      fullPath: '/api/remote/import'
      preLoaderRoute: typeof ApiRemoteImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/list': {
      id: '/api/agents/list'
      path: '/api/agents/list'
      fullPath: '/api/agents/list'
      preLoaderRoute: typeof ApiAgentsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/create': {
      id: '/api/agents/create'
      path: '/api/agents/create'
      fullPath: '/api/agents/create'
      preLoaderRoute: typeof ApiAgentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remotes_/$id/ping': {
      id: '/api/remotes_/$id/ping'
      path: '/api/remotes/$id/ping'
      fullPath: '/api/remotes/$id/ping'
      preLoaderRoute: typeof ApiRemotesIdPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remotes_/$id/pause': {
      id: '/api/remotes_/$id/pause'
      path: '/api/remotes/$id/pause'
      fullPath: '/api/remotes/$id/pause'
      preLoaderRoute: typeof ApiRemotesIdPauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/tools': {
      id: '/api/agents/$id/tools'
      path: '/api/agents/$id/tools'
      fullPath: '/api/agents/$id/tools'
      preLoaderRoute: typeof ApiAgentsIdToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/ship': {
      id: '/api/agents/$id/ship'
      path: '/api/agents/$id/ship'
      fullPath: '/api/agents/$id/ship'
      preLoaderRoute: typeof ApiAgentsIdShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/runs': {
      id: '/api/agents/$id/runs'
      path: '/api/agents/$id/runs'
      fullPath: '/api/agents/$id/runs'
      preLoaderRoute: typeof ApiAgentsIdRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/messages': {
      id: '/api/agents/$id/messages'
      path: '/api/agents/$id/messages'
      fullPath: '/api/agents/$id/messages'
      preLoaderRoute: typeof ApiAgentsIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/info': {
      id: '/api/agents/$id/info'
      path: '/api/agents/$id/info'
      fullPath: '/api/agents/$id/info'
      preLoaderRoute: typeof ApiAgentsIdInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/heartbeats': {
      id: '/api/agents/$id/heartbeats'
      path: '/api/agents/$id/heartbeats'
      fullPath: '/api/agents/$id/heartbeats'
      preLoaderRoute: typeof ApiAgentsIdHeartbeatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/chat': {
      id: '/api/agents/$id/chat'
      path: '/api/agents/$id/chat'
      fullPath: '/api/agents/$id/chat'
      preLoaderRoute: typeof ApiAgentsIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/agents/$id/status': {
      id: '/api/remote/agents/$id/status'
      path: '/api/remote/agents/$id/status'
      fullPath: '/api/remote/agents/$id/status'
      preLoaderRoute: typeof ApiRemoteAgentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/agents/$id/export': {
      id: '/api/remote/agents/$id/export'
      path: '/api/remote/agents/$id/export'
      fullPath: '/api/remote/agents/$id/export'
      preLoaderRoute: typeof ApiRemoteAgentsIdExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote/agents/$id/delete': {
      id: '/api/remote/agents/$id/delete'
      path: '/api/remote/agents/$id/delete'
      fullPath: '/api/remote/agents/$id/delete'
      preLoaderRoute: typeof ApiRemoteAgentsIdDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/tools/$toolId': {
      id: '/api/agents/$id/tools/$toolId'
      path: '/$toolId'
      fullPath: '/api/agents/$id/tools/$toolId'
      preLoaderRoute: typeof ApiAgentsIdToolsToolIdRouteImport
      parentRoute: typeof ApiAgentsIdToolsRoute
    }
    '/api/agents/$id/heartbeats/$hbId': {
      id: '/api/agents/$id/heartbeats/$hbId'
      path: '/$hbId'
      fullPath: '/api/agents/$id/heartbeats/$hbId'
      preLoaderRoute: typeof ApiAgentsIdHeartbeatsHbIdRouteImport
      parentRoute: typeof ApiAgentsIdHeartbeatsRoute
    }
  }
}

interface ApiRemotesRouteChildren {
  ApiRemotesIdRoute: typeof ApiRemotesIdRoute
}

const ApiRemotesRouteChildren: ApiRemotesRouteChildren = {
  ApiRemotesIdRoute: ApiRemotesIdRoute,
}

const ApiRemotesRouteWithChildren = ApiRemotesRoute._addFileChildren(
  ApiRemotesRouteChildren,
)

interface ApiToolsRouteChildren {
  ApiToolsIdRoute: typeof ApiToolsIdRoute
}

const ApiToolsRouteChildren: ApiToolsRouteChildren = {
  ApiToolsIdRoute: ApiToolsIdRoute,
}

const ApiToolsRouteWithChildren = ApiToolsRoute._addFileChildren(
  ApiToolsRouteChildren,
)

interface ApiAgentsIdHeartbeatsRouteChildren {
  ApiAgentsIdHeartbeatsHbIdRoute: typeof ApiAgentsIdHeartbeatsHbIdRoute
}

const ApiAgentsIdHeartbeatsRouteChildren: ApiAgentsIdHeartbeatsRouteChildren = {
  ApiAgentsIdHeartbeatsHbIdRoute: ApiAgentsIdHeartbeatsHbIdRoute,
}

const ApiAgentsIdHeartbeatsRouteWithChildren =
  ApiAgentsIdHeartbeatsRoute._addFileChildren(
    ApiAgentsIdHeartbeatsRouteChildren,
  )

interface ApiAgentsIdToolsRouteChildren {
  ApiAgentsIdToolsToolIdRoute: typeof ApiAgentsIdToolsToolIdRoute
}

const ApiAgentsIdToolsRouteChildren: ApiAgentsIdToolsRouteChildren = {
  ApiAgentsIdToolsToolIdRoute: ApiAgentsIdToolsToolIdRoute,
}

const ApiAgentsIdToolsRouteWithChildren =
  ApiAgentsIdToolsRoute._addFileChildren(ApiAgentsIdToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptainRoute: CaptainRoute,
  RemotesRoute: RemotesRoute,
  ToolsRoute: ToolsRoute,
  AgentsIdRoute: AgentsIdRoute,
  ApiRemotesRoute: ApiRemotesRouteWithChildren,
  ApiToolsRoute: ApiToolsRouteWithChildren,
  ApiAgentsCreateRoute: ApiAgentsCreateRoute,
  ApiAgentsListRoute: ApiAgentsListRoute,
  ApiRemoteImportRoute: ApiRemoteImportRoute,
  ApiRemoteInfoRoute: ApiRemoteInfoRoute,
  ApiRemotePauseRoute: ApiRemotePauseRoute,
  ApiRemoteResumeRoute: ApiRemoteResumeRoute,
  ApiSystemPauseRoute: ApiSystemPauseRoute,
  ApiSystemResumeRoute: ApiSystemResumeRoute,
  ApiSystemStatusRoute: ApiSystemStatusRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiAgentsIdChatRoute: ApiAgentsIdChatRoute,
  ApiAgentsIdHeartbeatsRoute: ApiAgentsIdHeartbeatsRouteWithChildren,
  ApiAgentsIdInfoRoute: ApiAgentsIdInfoRoute,
  ApiAgentsIdMessagesRoute: ApiAgentsIdMessagesRoute,
  ApiAgentsIdRunsRoute: ApiAgentsIdRunsRoute,
  ApiAgentsIdShipRoute: ApiAgentsIdShipRoute,
  ApiAgentsIdToolsRoute: ApiAgentsIdToolsRouteWithChildren,
  ApiRemotesIdPauseRoute: ApiRemotesIdPauseRoute,
  ApiRemotesIdPingRoute: ApiRemotesIdPingRoute,
  ApiRemoteAgentsIdDeleteRoute: ApiRemoteAgentsIdDeleteRoute,
  ApiRemoteAgentsIdExportRoute: ApiRemoteAgentsIdExportRoute,
  ApiRemoteAgentsIdStatusRoute: ApiRemoteAgentsIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
