/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAgentsIdChatRouteImport } from './routes/api/agents.$id.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIdChatRoute = ApiAgentsIdChatRouteImport.update({
  id: '/api/agents/$id/chat',
  path: '/api/agents/$id/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$id': typeof AgentsIdRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/agents/$id/chat': typeof ApiAgentsIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents/$id' | '/api/trpc/$' | '/api/agents/$id/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents/$id' | '/api/trpc/$' | '/api/agents/$id/chat'
  id: '__root__' | '/' | '/agents/$id' | '/api/trpc/$' | '/api/agents/$id/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsIdRoute: typeof AgentsIdRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiAgentsIdChatRoute: typeof ApiAgentsIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$id/chat': {
      id: '/api/agents/$id/chat'
      path: '/api/agents/$id/chat'
      fullPath: '/api/agents/$id/chat'
      preLoaderRoute: typeof ApiAgentsIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsIdRoute: AgentsIdRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiAgentsIdChatRoute: ApiAgentsIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
